version: 0.2

phases:
  install:
    commands:
      - echo Initalling source NPM depencies
      - yarn
  pre_build:
    commands:
      - npm nx --version

  build:
    commands:
      - echo Projects build started on `date`
      - echo Using variables
      - echo NODE_ENV = $NODE_ENV

      - echo Backend build started on `date`
      - yarn build
      - echo Backend build completed on `date`

  post_build:
    commands:
      # Creating deploy folder
      - mkdir som-web
      
      # populate dist into deploy folder
      - mkdir som-web/dist
      - cp -r out/* som-web/dist/
      
      # populate dist into deploy folder
      - mkdir som-web/pages
      - cp pages ./som-web/pages

      # Populate scripts into deploy folder
      - mkdir som-web/scripts
      - cp -r deploy/scripts/* som-web/scripts/
    
      # Populate server files into deploy folder
      - mkdir som-web/server-files
      - cp -r deploy/files/som-web-ssr.service som-web/server-files/som-web-ssr.service
      - cp -r deploy/files/nginx.config som-web/server-files/default

      - perl -pi -e "s/__SERVER_NAME__/$SERVER_NAME/g; s/__SSL_CERTIFICATE__/$SSL_CERTIFICATE/g; s/__SSL_CERTIFICATE_KEY__/$SSL_CERTIFICATE_KEY/g "  som-web/server-files/default
      
      # Get config files
      - cp package.json ./som-web/package.json
      - cp appspec.yml ./som-web/appspec.yml
      
      # Delete node_modules
      - rm -rf node_modules

      # List backck and frontend folders
      - ls ./som-web
artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    somweb:
      files:
        - '**/*'
      base-directory: som-web
    blah:
      files:
        - '**/*'
      base-directory: som-web